name: Publish TYPO3 Extension

on:
  workflow_call:
    secrets:
      access-token:
        required: true

jobs:
  publish:
    runs-on: alpine-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: tomasnorre/typo3-upload-ter@v2
        with:
          api-token: ${{ secrets.access-token }}
